name: rekyl
favicon: null
layout_spectrum: 0.9807067650835961
typography_spectrum: 0.561453104019165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.5970970652997494
  lightness: 0.8127184121403843
  saturation: 0.8825106334406883
  rhythmicContrast: 0.2829400822520256
purpose: []
